/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

//test here
    public static void main(String[] args)
    {

        iPhone myiPhone=new iPhone("myPhone","red","Apple",10);
        Person you=new Person("my","a long message ");
        AndroidMobile myAndroid=new AndroidMobile("myPhone","red","Apple",300);
        you.messageLimit(myiPhone);
        you.messageLimit(myAndroid);
        IPhoneRobot aRobot=new IPhoneRobot();
        aRobot.getPhone(myiPhone);
        aRobot.getPhone(myAndroid);

    }
}
